forkcms/library

spoon/database/database.php
spoon/tests/database/SpoonDatabaseLargeDataSet.php

While managing an activity log in forkcms backend, I got out of memory errors when I had around 800000 rows in my datagrid. It was caused by a bad way of determining the number of rows, using PDOStatement::fetchAll().
As quoted on http://php.net/manual/en/pdostatement.fetchall.php#refsect1-pdostatement.fetchall-returnvalues.
`Using this method to fetch large result sets will result in a heavy demand on system and possibly network resources.`
You will start seeing differences when you have 10000 rows or more.
Test below is counting 1000000 (one million) rows.
Old
```
$ phpunit --filter testGetNumRows spoon/tests/database/SpoonDatabaseLargeDataSet.php
PHPUnit 4.4.2 by Sebastian Bergmann.
Configuration read from /data/project/bart-forkcms-library/phpunit.xml.dist
.
Time: 420 ms, Memory: …
```

Spoon database: simple but very effective row count fix.

---

spoon/date/date.php

When using the getTimeAgo-method a lot of times f.e. in a datagrid, the locale-file is reloaded every time. This causes (big) performance issues in bigger datagrids. When using require_once, the loading only happens only once.

getTimeAgo: Use required_once instead of require

---

spoon/thumbnail/thumbnail.php

This current image is used as a reset for when the thumbnail is bigger then the original and it is not allowed to enlarge it.

Sets transparency for current thumbnail image

---

spoon/thumbnail/thumbnail.php

On https://github.com/forkcms/library/blob/master/spoon/thumbnail/thumbnail.php#L640 ```$currentImage``` gets destroyed, so we need to work on ```$this->image```.

Fix uploading gif

---

spoon/form/button.php
spoon/form/checkbox.php
spoon/form/date.php
spoon/form/dropdown.php
spoon/form/element.php
spoon/form/file.php
spoon/form/form.php
spoon/form/hidden.php
spoon/form/multi_checkbox.php
spoon/form/password.php
spoon/form/radiobutton.php
spoon/form/text.php
spoon/form/textarea.php
spoon/form/time.php

We want to convert to TwigTemplates in Fork, and we need to extend Spoon
to do it. We can't decently inject our TwigTemplates in these methods
when the typehint is in there though.

Remove typehints on SpoonTemplate.

---

spoon/template/compiler.php

In debug mode on a big template, this change can improve your page speed with more then 250ms.

Avoid recurring function calls in loops.

---

spoon/form/dropdown.php

When you submit an empty multiple dropdown, then it falls back on the default
values for the selected value, which gives unexpected results. This resets the
selected array for the field when it is submitted.

Fix empty submit of multiple dropdown

---

spoon/database/database.php

The $unixSocket must be set when using app/console in Fork CMS. Because
SpoonDatabase could not be found when using MAMP on a Mac.
Add unix_socket in **app/config/config.yml**
```yaml
services:
database:
class: SpoonDatabase
arguments:
- %database.driver%
- %database.host%
- %database.user%
- %database.password%
- %database.name%
- %database.port%
- %database.unix_socket%
```
And in **app/config/parameters.yml**
```yaml
parameters:
database.unix_socket:   /Applications/MAMP/tmp/mysql/mysql.sock
```

Added optional $unixSocket to SpoonDatabase

---

spoon/form/input.php
spoon/form/text.php
spoon/tests/form/SpoonFormTextTest.php

Some shorthand methods. This PR changes
```php
$form
->addText('email')
->setAttributes(array(
'required' => 'required',
'type' => 'email',
))
;
```
to
```php
$form
->addText('email')
->setType('email')
->makeRequired()
;
```

Forms syntax

---

spoon/database/database.php

on some php installs, 'SET NAMES utf8' and 'SET CHARACTER SET utf8' isn't enough.

Make sure our db always uses UTF8

---

spoon/template/compiler.php
spoon/tests/template/SpoonCompilerTest.php
spoon/tests/template/templates/template_modifier_iteration_over_array_of_objects.tpl
spoon/tests/template/templates/template_modifier_with_vars.tpl

Throw an exception when trying to use template modifiers on objects with variables
These would cause a parse error because the variables inside the the modifier call
would be rendered by surround it with the <?php ?> tag.

Bug modifier vars

---

spoon/form/form.php

When an action name contained quote characters, the form html breaks and
stuff could be injected in there. This is f.e. the case in the backend
of Fork CMS.
Related issue: https://github.com/forkcms/forkcms/issues/1405

Fix xss in SpoonForms.

---

spoon/datagrid/datagrid.php

Full [problem description](https://github.com/forkcms/forkcms/issues/2052).
Summary:
When giving a null to a SpoonDataGrid columnFunction, this will be converted to a string. But that isn't wanted behavior since we are using PHP 7.1 type casting.
The json_decode/encode is 3x faster then str_replace and ALSO fixes the problem. 
http://php.net/manual/en/function.str-replace.php

Fixes `null` values from being converted to empty string in SpoonDataGrid columnFunctions

---

spoon/filter/filter.php

**How I discovered bug**
I was using AJAX calls with multi-array post parameters.
f.e:
```
update_item[0][1] = 2
update_item[0][2] = 36
update_item[1][1] = 2
update_item[1][2] = 38
```
Then in the AJAX call, a $update = \SpoonFilter::getPostValue('update_item', null, null, 'array');
Which throws an Array to String conversion error.
The code in this PR fixes this "error thrown".

Bugfix when having multi-array arrays

---

spoon/form/checkbox.php
spoon/tests/form/SpoonFormCheckboxTest.php

Y and N are no longer used in fork, use 1 and 0 instead

Fix spoon form checkboxes not working in fork 5

---

spoon/datagrid/datagrid.php

There was a fix added to prevent null form turning into an empty string but that gave issues when the argument was a json or serialised string

Fix json as parameter for datagrid functions

---

composer.json

License “BSD” is not a valid SPDX license identifier, see https://spdx.org/licenses/
BSD 1 Clause seemed like the closest valid match, see https://spdx.org/licenses/BSD-1-Clause.html

Use a valid license identifier

---

spoon/tests/file/SpoonFileTest.php

Unit tests currently fail because they depend on an URL that should not exist. 
This PR changes this URL to a really non-existing one.

Fix unit tests

---

spoon/form/file.php
spoon/form/image.php

At this moment if you try to upload a SVG file this will most probably not work. Mostly because the PHP function `getimagesize` does not handle SVG. This PR intends to fix this problem.

Handle SVG file as a normal image

---

spoon/exception/exception.php

Since we only need this output in certain situations we don't have to render it every time.
A common occurrence was an exception containing an object originating from Doctrine that contains large objects or even circular references. Spoon would then attempt to use `var_dump` to display these objects causing memory issues.
This commit only attempts to dump variables when necessary, examples being debug mode or callbacks.
Most of the time Symfony's debug bundle will take care of error handling in those situations but when that's not available this still outputs all necessary data. Usually you will have a lot more memory available if you are running in debug mode.
Apologies in advance for the rather chaotic commit but the code styles were driving me crazy.

Extract a method to render an exception output

---

spoon/cookie/cookie.php

If a user sets a cookie containing an object it might execute some code inside the object when unserializing the object through the `__wakeup` magic method.
This pull request attempts to prevent this by setting and getting cookies through json encode/decode. We've also provided some fallback by checking if the cookie's string contains a serialized object. If it doesn't, we still unserialize the cookie and re-set it using `json_encode`. If the cookie does contain a serialized object an exception will be thrown.
This security fix _will_ break your website if objects are set in cookies.
See https://www.owasp.org/index.php/PHP_Object_Injection for example

Prevent object injection through unserialize

---

spoon/form/radiobutton.php

If the form uses numeric values, PHP will automatically cast them to
integers because we set them as array keys. If we don't cast it back to
a string we will compare an integer to a string and it will always fail.

Cast numeric values to strings

---

spoon/exception/exception.php

`$userAgent` variable is being used before it has been defined. This was probably caused by a refactoring a while ago.

Define missing userAgent variable

---

spoon/form/form.php

This fixes a security issue where Spoon would only check if a token was present in the session, and a form_token field was present in the form.
This would always validate as correct, since the form_token field is added in the constructor of the form with the value stored in the session if it exists. 
This allowed CSRF attacks to go through. 
The missing piece of the CSRF protection is to also validate against the $_GET and $_POST parameters. If no form_token parameter is present in those, then we're dealing with a CSRF attack.

Mark a form as incorrect when no CSRF token is present in the GET/POST

---

spoon/form/form.php

The previous fix only fixed checking if the token was submitted.
Further on in the code the submitted value was not used, instead the value of the automagically added field was used. Which made the check useless as it will alway be the same...

Check token correctly

---

spoon/form/text.php
spoon/tests/form/SpoonFormDateTest.php
spoon/tests/form/SpoonFormHiddenTest.php
spoon/tests/form/SpoonFormPasswordTest.php
spoon/tests/form/SpoonFormTextTest.php
spoon/tests/form/SpoonFormTimeTest.php

In #80, additional html encoding was added to rendered input fields to prevent XSS. For example in the datepicker of the Formbuilder module in Fork CMS. 
However, when you edit a page in Fork CMS the page title gets encoded two times. `&` turns into `&amp;` then into `&amp;amp;`
And when I debug the issue, in the `text.php` file of Spoon: 
* You can see that the getter will encode the value here: https://github.com/forkcms/library/blob/6b523ca2f760e16ae1aa474172cccbf7ba61ee89/spoon/form/text.php#L84-L89
* But the parse function also adds encoding since #80 https://github.com/forkcms/library/blob/6b523ca2f760e16ae1aa474172cccbf7ba61ee89/spoon/form/text.php#L791 and this is not necessary
So while other form fields (password, hidden, date, time, ...) did not do HTML encoding before #80, for …

Fix double encoding issue on text fields
