spoon/date/date.php

This fixes https://github.com/forkcms/library/commit/9d21f2ae912efeb5b7ab6f2702d407c9894e4707#commitcomment-10463745

Make sure no notices are thrown.

---

spoon/form/radiobutton.php
spoon/tests/form/SpoonFormRadiobuttonTest.php

As per [1194](https://github.com/forkcms/forkcms/issues/1194)

Bugfix integer valued radiobuttons.

---

spoon/form/text.php
spoon/tests/form/SpoonFormTextTest.php

Small PR makes isURL validation passing for urls without http://

Filter::isURL now auto appends http string if needed

---

spoon/database/database.php
spoon/tests/database/SpoonDatabaseTest.php

Allow us to insert/update DateTime objects in the database. Spoon Database will autoconvert these to a formatted date string.

Convert datetime

---

.travis.yml

Run travis on the container based infrastructure.

---

spoon/template/compiler.php
spoon/tests/template/SpoonCompilerTest.php
spoon/tests/template/templates/template_modifier.tpl
spoon/tests/template/templates/template_modifier_object.tpl

I noticed template modifiers didn't work when using objects instead of arrays. So I fixed it.

Object template modifiers

---

spoon/form/date.php
spoon/tests/form/SpoonFormDateTest.php

this should fix forkcms/forkcms#1556

Add extra date formats that are used in fork to the supported formats

---

spoon/form/text.php

The parameters weren't used correctly internally

Fix SpoonFormText::isPrice

---

spoon/form/form.php

In favor of private to ameliorate inheritance.

Change form method and property visibility to protected.

---

.travis.yml
composer.json
composer.lock
spoon/directory/directory.php
spoon/form/dropdown.php
spoon/tests/directory/SpoonDirectoryTest.php

Fixes html encoded characters like `'` (`&#039;`) in the values of dropdowns

Enable html encoded characters in the value

---

spoon/tests/form/SpoonFormRadiobuttonTest.php

Trying to identify all the typing issues that can possibly occur to remind/inform us.
Request for comment/advice.

RFC: Add a failing test for Radiobutton.

---

spoon/form/form.php

func_get_args doesn't like it when you do that..

Don't overwrite the parameter variable in the first line

---

README.md

We no longer use phpunit, update the README f

Update readme, we use phpunit-bridge instead of phpunit

---

spoon/database/database.php

currently true is transformed to 1 but false to "" and that gives errors

Change booleans to 1 or 0 when trying to pass them to the database

---

.travis.yml
composer.json
composer.lock

Fork requires 7.1 and if we bump it now then we can also use the new language features here if we want/need to

Require php 7.1

---

spoon/template/compiler.php

Changed count() == 0 and count() != 0 to empty() === true and empty() === false, for compatability of the iterations in the datagrid template.

Changed count for compatability with php 7.2

---

spoon/form/dropdown.php

The dropdown is parsed multiple times resulting in name[][] instead of name[]

Fix multiple select issue with twig

---

spoon/cookie/cookie.php

This is the version 1 version of #69

Prevent object injection through unserialize

---

spoon/database/database.php

See https://github.com/forkcms/forkcms/issues/2996

A float should not be using PDO::PARAM_INT

---

spoon/tests/SpoonTest.php
spoon/tests/database/SpoonDatabaseLargeDataSet.php
spoon/tests/database/SpoonDatabaseTest.php
spoon/tests/datagrid/SpoonDataGridTest.php
spoon/tests/date/SpoonDateTest.php
spoon/tests/directory/SpoonDirectoryTest.php
spoon/tests/feed/SpoonFeedRSSTest.php
spoon/tests/file/SpoonFileTest.php
spoon/tests/filter/SpoonFilterIsURLTest.php
spoon/tests/filter/SpoonFilterTest.php
spoon/tests/form/SpoonFileFieldTest.php
spoon/tests/form/SpoonFormButtonTest.php
spoon/tests/form/SpoonFormCheckboxTest.php
spoon/tests/form/SpoonFormDateTest.php
spoon/tests/form/SpoonFormDropdownTest.php
spoon/tests/form/SpoonFormHiddenTest.php
spoon/tests/form/SpoonFormMultiCheckBoxTest.php
spoon/tests/form/SpoonFormPasswordTest.php
spoon/tests/form/SpoonFormRadiobuttonTest.php
spoon/tests/form/SpoonFormTest.php
spoon/tests/form/SpoonFormTextTest.php
spoon/tests/form/SpoonFormTextareaTest.php
spoon/tests/form/SpoonFormTimeTest.php
spoon/tests/locale/SpoonLocaleTest.php
spoon/tests/template/SpoonCompilerTest.php
spoon/tests/template/SpoonModifiersTest.php
spoon/tests/template/SpoonTemplateTest.php
spoon/tests/thumbnail/SpoonThumbnailTest.php

Refactor the tests to run on PHP7+ and PHPunit 6.5.1

Refactor tests

---

spoon/form/attributes.php

There was an issue with xss in form attributes. xss strings could for instance be injected in placeholders

Fix xss issue with form attributes

---

spoon/form/attributes.php
spoon/form/date.php
spoon/form/hidden.php
spoon/form/password.php
spoon/form/text.php
spoon/form/time.php

@carakas (https://huntr.dev/users/carakas) has fixed a potential XSS in Spoon form types hidden, date and time vulnerability in your repository 🔨. For more information, visit our website (https://huntr.dev/) or click the bounty URL below...
Q | A
Version Affected | 1.3.1 - 3.2.8
Bug Fix | YES
Original Pull Request | https://github.com/418sec/library-1/pull/1
If you are happy with this disclosure, we would love to get a CVE assigned to the vulnerability. Feel free to credit @carakas, the discloser found in the bounty URL (below) and @huntr-helper.
_Please enter the direct URL for this bounty on huntr.dev. This is compulsory and will help us process your bounty submission quicker._
_Describe your fix clearly and concisely - imagine you are describing it to a non-technical friend._
The form …

Security Fix for XSS in Spoon form types hidden, date and time - huntr.dev
